// Not copyrighted - public domain.
//
// This sample parser implementation was generated by CodeSynthesis XSD,
// an XML Schema to C++ data binding compiler. You may use it in your
// programs without any restrictions.
//

#ifndef MOL_SIM_PIMPL_H
#define MOL_SIM_PIMPL_H

#include "MolSim-pskel.h"

class input_file_pimpl: public virtual input_file_pskel,
  public ::xml_schema::string_pimpl
{
  public:
  virtual void
  pre ();

  virtual void
  post_input_file ();

  virtual std::string
  get_input_file();

  private:
    std::string input_file;
};

class delta_t_pimpl: public virtual delta_t_pskel,
  public ::xml_schema::double_pimpl
{
  public:
  virtual void
  pre ();

  virtual void
  post_delta_t ();

  virtual double&
  get_delta_t();

 private:
    double delta_t;
};

class end_time_pimpl: public virtual end_time_pskel,
  public ::xml_schema::double_pimpl
{
  public:
  virtual void
  pre ();

  virtual void
  post_end_time ();

  virtual double&
  get_end_time();

private:
    double end_time;
};

class output_step_pimpl: public virtual output_step_pskel,
  public ::xml_schema::int_pimpl
{
  public:
  virtual void
  pre ();

  virtual void
  post_output_step ();

  virtual int&
  get_output_step();

private:
    int output_step;
};

class algorithm_pimpl: public virtual algorithm_pskel,
  public ::xml_schema::string_pimpl
{
  public:
  virtual void
  pre ();

  virtual void
  post_algorithm ();

  virtual std::string
  get_algorithm();

private:
    std::string algorithm;
};

class benchmark_pimpl: public virtual benchmark_pskel,
  public ::xml_schema::string_pimpl
{
  public:
  virtual void
  pre ();

  virtual void
  post_benchmark ();

  virtual std::string
  get_benchmark();

private:
    std::string benchmark;
};

class molsim_pimpl: public virtual molsim_pskel
{
  public:
  virtual void
  pre ();

  virtual void
  input_file ();

  virtual void
  delta_t ();

  virtual void
  end_time ();

  virtual void
  output_step ();

  virtual void
  algorithm ();

  virtual void
  benchmark ();

  virtual void
  post_molsim ();

};

#endif // MOL_SIM_PIMPL_H
