// Not copyrighted - public domain.
//
// This sample parser implementation was generated by CodeSynthesis XSD,
// an XML Schema to C++ data binding compiler. You may use it in your
// programs without any restrictions.
//

#include "MolSim-pimpl.h"

// input_file_pimpl
//

void input_file_pimpl::
pre ()
{
}

void input_file_pimpl::
post_input_file ()
{
  const ::std::string& v (post_string ());

  // TODO
  input_file = v;
  //
}

std::string input_file_pimpl::get_input_file() {
    return input_file;
}

// delta_t_pimpl
//

void delta_t_pimpl::
pre ()
{
}

void delta_t_pimpl::
post_delta_t ()
{
  double v (post_double ());

  // TODO
  delta_t = v;
  //
}

double delta_t_pimpl::get_delta_t() {
    return delta_t;
}

// end_time_pimpl
//

void end_time_pimpl::
pre ()
{
}

void end_time_pimpl::
post_end_time ()
{
  double v (post_double ());

  // TODO
  end_time = v;
  //
}

double end_time_pimpl::get_end_time() {
    return end_time;
}
// output_step_pimpl
//

void output_step_pimpl::
pre ()
{
}

void output_step_pimpl::
post_output_step ()
{
  int v (post_int ());

  // TODO
  output_step = v;
  //
}

int output_step_pimpl::get_output_step() {
    return output_step;
}
// epsilon_pimpl
//

void epsilon_pimpl::
pre ()
{
}

void epsilon_pimpl::
post_epsilon ()
{
  double v (post_double ());

  // TODO
  epsilon = v;
  //
}

double epsilon_pimpl::get_epsilon() {
    return epsilon;
}

// sigma_pimpl
//

void sigma_pimpl::
pre ()
{
}

void sigma_pimpl::
post_sigma ()
{
  double v (post_double ());

  // TODO
  sigma = v;
  //
}

double sigma_pimpl::get_sigma() {
    return sigma;
}

// averageV_pimpl
//

void averageV_pimpl::
pre ()
{
}

void averageV_pimpl::
post_averageV ()
{
  double v (post_double ());

  // TODO
  averageV = v;
  //
}

double averageV_pimpl::get_averageV() {
    return averageV;
}
// dimension_pimpl
//

void dimension_pimpl::
pre ()
{
}

void dimension_pimpl::
x (int x)
{
  // TODO
  x_ = x;
  //
}

void dimension_pimpl::
y (int y)
{
  // TODO
  y_ = y;
  //
}

void dimension_pimpl::
z (int z)
{
  // TODO
  z_ = z;
  //
}

void dimension_pimpl::
post_dimension ()
{
}

int dimension_pimpl::getX() {
    return x_;
}
int dimension_pimpl::getY() {
    return y_;
}
int dimension_pimpl::getZ() {
    return z_;
}

// mesh_pimpl
//

void mesh_pimpl::
pre ()
{
}

void mesh_pimpl::
post_mesh ()
{
  double v (post_double ());

  // TODO
  mesh = v;
  //
}

double mesh_pimpl::get_mesh() {
    return mesh;
}
// cutoff_pimpl
//

void cutoff_pimpl::
pre ()
{
}

void cutoff_pimpl::
post_cutoff ()
{
  double v (post_double ());

  // TODO
  cutoff = v;
  //
}

double cutoff_pimpl::get_cutoff() {
    return cutoff;
}
// algorithm_pimpl
//

void algorithm_pimpl::
pre ()
{
}

void algorithm_pimpl::
post_algorithm ()
{
  const ::std::string& v (post_string ());

  // TODO
    algorithm = v;
  //
}

std::string algorithm_pimpl::get_algorithm() {
    return algorithm;
}

// benchmark_pimpl
//

void benchmark_pimpl::
pre ()
{
}

void benchmark_pimpl::
post_benchmark ()
{
  const ::std::string& v (post_string ());

  // TODO
  benchmark = v;
  //
}

std::string benchmark_pimpl::get_benchmark() {
    return benchmark;
}

// molsim_pimpl
//

void molsim_pimpl::
pre ()
{
}

void molsim_pimpl::
input_file ()
{
}

void molsim_pimpl::
delta_t ()
{
}

void molsim_pimpl::
end_time ()
{
}

void molsim_pimpl::
output_step ()
{
}

void molsim_pimpl::
epsilon ()
{
}

void molsim_pimpl::
sigma ()
{
}

void molsim_pimpl::
averageV ()
{
}

void molsim_pimpl::
dimension ()
{
}

void molsim_pimpl::
mesh ()
{
}

void molsim_pimpl::
cutoff ()
{
}

void molsim_pimpl::
algorithm ()
{
}

void molsim_pimpl::
benchmark ()
{
}

void molsim_pimpl::
post_molsim ()
{
}

