// Not copyrighted - public domain.
//
// This sample parser implementation was generated by CodeSynthesis XSD,
// an XML Schema to C++ data binding compiler. You may use it in your
// programs without any restrictions.
//

#ifndef MOL_SIM_PIMPL_H
#define MOL_SIM_PIMPL_H

#include "MolSim-pskel.h"

class input_file_pimpl: public virtual input_file_pskel,
  public ::xml_schema::string_pimpl
{
  public:
  virtual void
  pre ();

  virtual void
  post_input_file ();

  virtual std::string
  get_input_file();

  private:
    std::string input_file;
};

class delta_t_pimpl: public virtual delta_t_pskel,
  public ::xml_schema::double_pimpl
{
  public:
  virtual void
  pre ();

  virtual void
  post_delta_t ();

  virtual double
  get_delta_t();

  private:
    double delta_t;
};

class end_time_pimpl: public virtual end_time_pskel,
  public ::xml_schema::double_pimpl
{
  public:
  virtual void
  pre ();

  virtual void
  post_end_time ();

  virtual double
  get_end_time();

private:
    double end_time;
};

class output_step_pimpl: public virtual output_step_pskel,
  public ::xml_schema::int_pimpl
{
  public:
  virtual void
  pre ();

  virtual void
  post_output_step ();

  virtual int
  get_output_step();

private:
    int output_step;
};

class epsilon_pimpl: public virtual epsilon_pskel,
  public ::xml_schema::double_pimpl
{
  public:
  virtual void
  pre ();

  virtual void
  post_epsilon ();

  virtual double
  get_epsilon();

private:
    double epsilon;
};

class sigma_pimpl: public virtual sigma_pskel,
  public ::xml_schema::double_pimpl
{
  public:
  virtual void
  pre ();

  virtual void
  post_sigma ();

  virtual double
  get_sigma();

private:
    double sigma;
};

class averageV_pimpl: public virtual averageV_pskel,
  public ::xml_schema::double_pimpl
{
  public:
  virtual void
  pre ();

  virtual void
  post_averageV ();

    virtual double
    get_averageV();

private:
    double averageV;
};

class dimension_pimpl: public virtual dimension_pskel
{
  public:
  virtual void
  pre ();

  virtual void
  x (int);

  virtual void
  y (int);

  virtual void
  z (int);

  virtual void
  post_dimension ();

    virtual int
    getX();

    virtual int
    getY();

    virtual int
    getZ();

private:
    int x_;
    int y_;
    int z_;
};

class mesh_pimpl: public virtual mesh_pskel,
  public ::xml_schema::double_pimpl
{
  public:
  virtual void
  pre ();

  virtual void
  post_mesh ();

  virtual double
  get_mesh();

private:
    double mesh;
};

class cutoff_pimpl: public virtual cutoff_pskel,
  public ::xml_schema::double_pimpl
{
  public:
  virtual void
  pre ();

  virtual void
  post_cutoff ();

  virtual double
  get_cutoff();

private:
    double cutoff;
};

class algorithm_pimpl: public virtual algorithm_pskel,
  public ::xml_schema::string_pimpl
{
  public:
  virtual void
  pre ();

  virtual void
  post_algorithm ();

  virtual std::string
  get_algorithm();

private:
    std::string algorithm;
};

class benchmark_pimpl: public virtual benchmark_pskel,
  public ::xml_schema::string_pimpl
{
  public:
  virtual void
  pre ();

  virtual void
  post_benchmark ();

  virtual std::string
  get_benchmark();

private:
    std::string benchmark;
};

class molsim_pimpl: public virtual molsim_pskel
{
  public:
  virtual void
  pre ();

  virtual void
  input_file ();

  virtual void
  delta_t ();

  virtual void
  end_time ();

  virtual void
  output_step ();

  virtual void
  epsilon ();

  virtual void
  sigma ();

  virtual void
  averageV ();

  virtual void
  dimension ();

  virtual void
  mesh ();

  virtual void
  cutoff ();

  virtual void
  algorithm ();

  virtual void
  benchmark ();

  virtual void
  post_molsim ();
};

#endif // MOL_SIM_PIMPL_H
